### ISSUE TITLE
Reverse operation

### ISSUE THREAD

**Issue by Draghmar** [jfcherng-sublime/ST-RainbowIndent#3]
Hi
Is it possible to set RainbowIndent to work in reverse? So I could use shortcut to enable it when I need it?
Why? In most cases I don't need to look at indent so closely so I don't need the distraction that additional colours introduce. But occasionally I do need to check indent and it would be great to be able to toggle it on.

**Comment by jfcherng** [comment]
My first thought would be you set 

```js
    // Enable this plugin in these base scopes.
    // For the expression of a scope selector, see https://www.sublimetext.com/docs/selectors.html
    "enabled_selector": "I do not want to enable by default",
```

so this plugin never renders indent by default (since no syntax `scope` will ever match `I do not want to enable by default`) and then you either force enabling the rendering from the context menu 

![image](https://github.com/jfcherng-sublime/ST-RainbowIndent/assets/6594915/f18a43c1-8977-4f19-8ce1-ce44dcd275b7)

or you assign a keybinding for toggling the "force enable/disable" status.
https://github.com/jfcherng-sublime/ST-RainbowIndent/issues/1#issuecomment-2110203667
The command name is `rainbow_indent_view_toggle` for keybinding.

**Comment by jfcherng** [comment]
Closed due to inactivity.
